config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments, only: [:create]
  end
  resources :exams
  resources :search
  resources :subjects
  resources :departments
  resources :year_groups
  resources :events
  devise_for :users
  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  
  mount_uploader :image, EventImageUploader
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def self.future
    where('date>=?', Date.today)
  end
  
  def self.date_order
    order(date: :asc)
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/event_department.rb
class EventDepartment < ActiveRecord::Base
  belongs_to :event
  belongs_to :department
end

app/models/event_year_group.rb
class EventYearGroup < ActiveRecord::Base
  belongs_to :event
  belongs_to :year_group
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :year_group
      validates_presence_of :year_group_id
  mount_uploader :image, EventImageUploader
  def self.search(search)
    where("sub_name LIKE ?", "%#{search}%")
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :year_group
  has_many :comments
    mount_uploader :image, EventImageUploader
    validates_presence_of :year_group_id
    
end

app/models/subject.rb
class Subject < ActiveRecord::Base
    belongs_to :year_group
    validates_presence_of :year_group_id

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :comments
end

app/models/year_group.rb
class YearGroup < ActiveRecord::Base
    has_many :subjects
    has_many :posts
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:user_id, :name, :description, :date, :start_time, :end_time, :status, :image)
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:sub_name, :grade, :start_date, :start_time, :image, :description, :year_group_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @upcoming_events = Event.future.date_order
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image, :category, :year_group_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_date_time(date, start_time, end_time)
        date.strftime("%A, %d %b %y") + '' + \
         start_time.strftime('l:%M%P') + '-' + \
     end_time.strftime("%l:%M%P")
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/year_groups_helper.rb
module YearGroupsHelper
end

app/views/events/_event.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h2 class="panel-title">
            <%= event.name %>
            <span class="pull-right">
                <%= format_date_time(event.date,event.start_time, event.end_time) %>
            </span>
        </h2>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
            <%= image_tag event.image, class: "img-responsive" %>
            </div>
            <div class="col-md-8">
                <p class= "lead"><%= event.description %></p>
                <p></p>
                <%= link_to "More info", event_path(event), class:"btn btn-info btn-xs" %>
            </div>
        </div>
    </div>
</div>

app/views/events/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    
    <%= f.input :name, label:"Enter the event name" %>
    <%= f.input :description, placeholder:'Please provide details of the event' %>
    <%= f.input :date, order: [:day, :month, :year], start_year: Date.today.year, end_year: Date.today.year + 1 %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
        </div>
      </div>
    </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
     
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Status</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        
        <td><%= event.name %></td>
        
        <td><%= event.date.strftime('%a, %d %b %y') %></td>
        <td><%= event.start_time.strftime('%l:%M%P') %></td>
        <td><%= event.end_time.strftime('%l:%M%P') %></td>
        <td><%= event.status %></td>
       
        <td class ="button"><%= link_to 'Show', event %></td>
        <td class ="button"><%= link_to 'Edit', edit_event_path(event) %></td>
        <td class ="button"><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path, class:'btn btn-success' %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title"><%= @event.name %></h2>
      </div>
      <div class="panel body">
        <%= image_tag @event.image, class:"img-responsive img-thubnail" %>
        <p><%= @event.description %></p>
        <hr>
        <p><strong>When: </strong><%= @event.date.strftime('%A, %d %B %Y') %> <%= @event.start_time.strftime('l:%M%P') %> - <%= @event.end_time.strftime('%l:%M%P') %></p>
      </div>
    </div>
  </div>
</div>
<p>
  <strong>User's email:</strong>
  <%= @event.user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @event.status %>
</p>

<p>
  <strong>Image:</strong>
  <%= @event.image %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/exams/_form.html.erb
        
<%= simple_form_for(@exam) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :sub_name %>
    <%= f.input :grade, placeholder: "class" %>
    <%= f.input :start_date %>
    <%= f.input :start_time,placeholder: "enter the exam period" %>
    <%= f.input :image, as: :file%>
    <%= f.input :description %>
    <%= f.association :year_group %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exams</h1>

<table class="table">
  <thead>
    <tr>
      <th>Sub name</th>
      <th>Grade</th>
      <th>Start date</th>
      <th>Start time</th>
      <th>Description</th>
      <th>Year group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.sub_name %></td>
        <td><%= exam.grade %></td>
        <td><%= exam.start_date %></td>
        <td><%= exam.start_time %></td>
        <td><%= truncate(exam.description) %></td>
        <td><%= exam.year_group.name %></td>
        <td class ="button"><%= link_to 'Show', exam %></td>
        <td class ="button"><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td class ="button"><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<td><%= link_to 'New Exam', new_exam_path, class:  'btn btn-success btn-xs' %></td>

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form' %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sub name:</strong>
  <%= @exam.sub_name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @exam.grade %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @exam.start_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @exam.start_time %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @exam.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exam.description %>
</p>

<p>
  <strong>Year group:</strong>
  <%= @exam.year_group.name %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :image, as: :file %>
    <%= f.input :category %>
    <%= f.association :year_group %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <th>Year group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
    
            <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.category %></td>
        <td><%= post.year_group.name %></td>
        </div>
        <td class ="button"><%= link_to 'Show', post %></td>
        <td class ="button"><%= link_to 'Edit', edit_post_path(post) %></td>
        <td class ="button"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class ="row">
    <div class="col-md-8">
    </div>
</div>
<td><%= link_to 'New Post',new_post_path, class:  'btn btn-success btn-xs' %></td>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong class = "post-style">Title:</strong> 
  <%= @post.title %>
</p>

<p>
  <strong class = "post-style">Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong class = "post-style">Image:</strong>
  <%= @post.image %>
</p>

<p>
  <strong class = "post-style">Category:</strong>
  <%= @post.category %>
</p>

<p>
  <strong >Year group:</strong>
  <%= @post.year_group.name %>
</p>
<p>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<%= form_for [@post,Comment.new] do |f| %></p>
  <p><%= f.label @post,"New Comment"%></p>
  <p><%= f.text_area :body %></p>
  <p><%= f.submit "Add comment" %></p> 
<% end %>
<h1> Comments </h1>
<%= render partial: @post.comments %>