config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments, only: [:create]
  end
  resources :exams
  resources :search
  resources :subjects
  resources :departments
  resources :year_groups
  resources :events
  devise_for :users
  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  
  mount_uploader :image, EventImageUploader
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def self.future
    where('date>=?', Date.today)
  end
  
  def self.date_order
    order(date: :asc)
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/event_department.rb
class EventDepartment < ActiveRecord::Base
  belongs_to :event
  belongs_to :department
end

app/models/event_year_group.rb
class EventYearGroup < ActiveRecord::Base
  belongs_to :event
  belongs_to :year_group
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :year_group
      validates_presence_of :year_group_id
  mount_uploader :image, EventImageUploader
  def self.search(search)
    where("sub_name LIKE ?", "%#{search}%")
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :year_group
  has_many :comments
    mount_uploader :image, EventImageUploader
    validates_presence_of :year_group_id
    
end

app/models/subject.rb
class Subject < ActiveRecord::Base
    belongs_to :year_group
    validates_presence_of :year_group_id

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :comments
end

app/models/year_group.rb
class YearGroup < ActiveRecord::Base
    has_many :subjects
    has_many :posts
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @upcoming_events = Event.future.date_order
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_date_time(date, start_time, end_time)
        date.strftime("%A, %d %b %y") + '' + \
         start_time.strftime('l:%M%P') + '-' + \
     end_time.strftime("%l:%M%P")
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/year_groups_helper.rb
module YearGroupsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Blacktown Girls High School</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="active"><a href="/year_groups">Year Group <span class="sr-only">(current)</span></a></li>
            <li><a href="/posts/new">Add Posts</a></li>
            <li><a href="/exams/new">Add Exams</a></li>
            <li><a href="/subjects/new">Add Subjects</a></li>
            <li><a href="/events">Events</a></li>
            <li role="separater" class="divider"></li>
            <!--<li><a href="#'>Separated link</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">One more separated link</a></li>-->
      </ul>
      </li>
      </ul>
      <%= form_tag(search_index_path, method: :get, class: 'navbar-form navbar-left') do %>
      <%= text_field_tag(:search, params[:search], placeholder: "Search Events & Exams", class: 'form-group form-control') %>
      <%= submit_tag "search", class: 'btn btn-default' %>
      <%end %>
      
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><a href="/">Logged in as <%=current_user.email%></a></li>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %><li/>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BGHS Events</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar'%>
<div class='container'>
  <%= yield %>
</div>
</body>
</html>